title: Micah Flack
url: "https://micahflack.com/"
baseurl: ""

markdown: kramdown
#ins_logo: "./favicon-32x32png"

#tracking_id: #

footer: no
#footer_url: ""
#footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "docs/resume.pdf"
 - name: "Publications"
   link: "#publications"
 - name: "Projects"
   link: "#projects"
 - name: "Contact"
   link: "contact"

